---
- name: Get Drupal and Drush paths
  include_vars:
    drush: '~/bin/drush'
    drupal_root: '~/drupal'

- name: Get Drush version
  shell: 'cd {{ drupal_root }} && {{ drush }} version | sed -E "s/[A-Za-z: ]+([0-9\.]+)/\1/"'
  register: get_drush_version

- set_fact: 
    drush_version: '{{ get_drush_version.stdout.split(".") }}'

- name: Get Drupal version
  shell: 'cd {{ drupal_root }}/web && {{ drush }} status | sed -En "s/\sDrupal version\s+:\s+([0-9\.]+)/\1/p"'
  register: get_drupal_version

- set_fact: 
    drupal_version: '{{ get_drupal_version.stdout.split(".") }}'