all:
  hosts:
    production:
      ansible_user: 
      ansible_password: 
      ansible_host: 
      ansible_port: 
    origin:
      ansible_user: 
      ansible_password: 
      ansible_host: 
      ansible_port: 
