all:
  hosts:
    production:
      ansible_user: southernperform
      ansible_remote_tmp: "~/tmp"
    origin:
      ansible_user: treloardigitalco
  vars:
    ansible_host: cp-kil-m-009.micron21.com
    ansible_port: 21212
